import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { createServer } from "./server";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  server: {
    host: "::",
    port: 8080,
    fs: {
      allow: [
        path.resolve(__dirname),
        path.resolve(__dirname, "./client"),
        path.resolve(__dirname, "./shared"),
        path.resolve(__dirname, "./node_modules"),
      ],
      deny: [".env", ".env.*", "*.{crt,pem}", "**/.git/**", "server/**"],
    },
  },
  build: {
    outDir: "dist/spa",
    // Explicitly disable browser sourcemaps in production builds to avoid
    // leaking internal file structure in the browser devtools.
    sourcemap: mode === "development",
    // Minification settings (esbuild is built-in and avoids requiring terser types)
    minify: "esbuild",
    esbuild: {
      drop: mode === "production" ? ["console", "debugger"] : [],
    },
    rollupOptions: {
      output: {
        manualChunks: {
          // Split vendor code for better caching and parallel loading
          "vendor-react": ["react", "react-dom", "react-router-dom"],
          "vendor-ui": [
            "@radix-ui/react-accordion",
            "@radix-ui/react-alert-dialog",
            "@radix-ui/react-aspect-ratio",
            "@radix-ui/react-avatar",
            "@radix-ui/react-checkbox",
            "@radix-ui/react-collapsible",
            "@radix-ui/react-dialog",
            "@radix-ui/react-dropdown-menu",
            "@radix-ui/react-label",
            "@radix-ui/react-popover",
            "@radix-ui/react-select",
            "@radix-ui/react-tabs",
            "@radix-ui/react-toggle",
          ],
          "vendor-animations": ["framer-motion"],
          "vendor-charts": ["recharts"],
        },
      },
    },
  },
  plugins: [
    react(),
    expressPlugin(),
    nonBlockingStylesPlugin(),
    // sitemap plugin removed; sitemaps are generated by WordPress/Yoast at /cms
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./client"),
      "@shared": path.resolve(__dirname, "./shared"),
    },
    dedupe: ["react", "react-dom"],
  },
}));

function expressPlugin(): Plugin {
  return {
    name: "express-plugin",
    apply: "serve",
    configureServer(server) {
      const app = createServer();
      server.middlewares.use(app);
    },
  };
}

function nonBlockingStylesPlugin(): Plugin {
  return {
    name: "non-blocking-styles-plugin",
    apply: "build",
    transformIndexHtml(html) {
      return html.replace(
        /<link rel="stylesheet"([^>]*href="(\/assets\/[^"]+\.css)"[^>]*)>/g,
        (_full, attrs: string, href: string) => {
          const hasCrossorigin = /\bcrossorigin\b/.test(attrs);
          const crossoriginAttr = hasCrossorigin ? " crossorigin" : "";
          return [
            `<link rel="preload" as="style" href="${href}"${crossoriginAttr} onload="this.onload=null;this.rel='stylesheet'">`,
            `<noscript><link rel="stylesheet" href="${href}"${crossoriginAttr}></noscript>`,
          ].join("\n    ");
        },
      );
    },
  };
}
