import { defineField, defineType } from "sanity";

export const sectionSettings = defineType({
  name: "sectionSettings",
  title: "Section Settings",
  type: "object",
  options: { collapsible: true, collapsed: true },
  fields: [
    defineField({
      name: "anchorId",
      title: "Anchor ID",
      type: "string",
      description:
        "Optional HTML id for scroll-to links (e.g. 'pricing' → #pricing).",
      validation: (Rule) =>
        Rule.regex(/^[a-z][a-z0-9-]*$/, {
          name: "slug",
          invert: false,
        }).warning("Use lowercase letters, numbers, and hyphens only."),
    }),
    defineField({
      name: "backgroundColor",
      title: "Background Preset",
      type: "string",
      initialValue: "default",
      options: {
        list: [
          { title: "Default", value: "default" },
          { title: "Dark", value: "dark" },
          { title: "Darker", value: "darker" },
          { title: "Accent (Cyan/Blue)", value: "accent" },
          { title: "Gradient", value: "gradient" },
          { title: "White", value: "white" },
          { title: "Custom", value: "custom" },
        ],
        layout: "radio",
      },
    }),
    defineField({
      name: "customBackgroundColor",
      title: "Custom Background Color",
      type: "color",
      description: "Pick any color with hex, RGB, and opacity.",
      options: { disableAlpha: false },
      hidden: ({ parent }) => parent?.backgroundColor !== "custom",
    }),
    defineField({
      name: "backgroundImage",
      title: "Background Image",
      type: "image",
      description: "Optional background image behind the section.",
      options: { hotspot: true },
    }),
    defineField({
      name: "backgroundOverlay",
      title: "Background Overlay",
      type: "string",
      description: "Darkens the background image so text remains readable.",
      initialValue: "60",
      options: {
        list: [
          { title: "None", value: "0" },
          { title: "Light (20%)", value: "20" },
          { title: "Medium (40%)", value: "40" },
          { title: "Heavy (60%)", value: "60" },
          { title: "Very Heavy (80%)", value: "80" },
        ],
      },
      hidden: ({ parent }) => !parent?.backgroundImage,
    }),
    defineField({
      name: "fontFamily",
      title: "Font Family",
      type: "string",
      description: "Override the section's font family.",
      options: {
        list: [
          { title: "Site Default (Space Grotesk)", value: "default" },
          { title: "Inter", value: "Inter" },
          { title: "Poppins", value: "Poppins" },
          { title: "DM Sans", value: "DM Sans" },
          { title: "Plus Jakarta Sans", value: "Plus Jakarta Sans" },
          { title: "Outfit", value: "Outfit" },
          { title: "Sora", value: "Sora" },
          { title: "Raleway", value: "Raleway" },
          { title: "Montserrat", value: "Montserrat" },
          { title: "Lato", value: "Lato" },
          { title: "Open Sans", value: "Open Sans" },
          { title: "Rubik", value: "Rubik" },
          { title: "Work Sans", value: "Work Sans" },
          { title: "Manrope", value: "Manrope" },
          { title: "Nunito Sans", value: "Nunito Sans" },
          { title: "Source Sans 3", value: "Source Sans 3" },
          { title: "Josefin Sans", value: "Josefin Sans" },
          { title: "Barlow", value: "Barlow" },
          { title: "Mulish", value: "Mulish" },
          { title: "Libre Franklin", value: "Libre Franklin" },
          { title: "IBM Plex Sans", value: "IBM Plex Sans" },
          { title: "Figtree", value: "Figtree" },
          { title: "Onest", value: "Onest" },
          { title: "Geist", value: "Geist" },
        ],
      },
    }),
    defineField({
      name: "paddingTop",
      title: "Padding Top",
      type: "string",
      initialValue: "md",
      options: {
        list: [
          { title: "None", value: "none" },
          { title: "Small", value: "sm" },
          { title: "Medium", value: "md" },
          { title: "Large", value: "lg" },
          { title: "Extra Large", value: "xl" },
        ],
        layout: "radio",
      },
    }),
    defineField({
      name: "paddingBottom",
      title: "Padding Bottom",
      type: "string",
      initialValue: "md",
      options: {
        list: [
          { title: "None", value: "none" },
          { title: "Small", value: "sm" },
          { title: "Medium", value: "md" },
          { title: "Large", value: "lg" },
          { title: "Extra Large", value: "xl" },
        ],
        layout: "radio",
      },
    }),
    defineField({
      name: "containerWidth",
      title: "Container Width",
      type: "string",
      initialValue: "default",
      options: {
        list: [
          { title: "Narrow", value: "narrow" },
          { title: "Default", value: "default" },
          { title: "Wide", value: "wide" },
          { title: "Full Width", value: "full" },
        ],
        layout: "radio",
      },
    }),
    defineField({
      name: "textAlign",
      title: "Text Alignment",
      type: "string",
      initialValue: "left",
      options: {
        list: [
          { title: "Left", value: "left" },
          { title: "Center", value: "center" },
          { title: "Right", value: "right" },
        ],
        layout: "radio",
      },
    }),
    defineField({
      name: "hideOnMobile",
      title: "Hide on Mobile",
      type: "boolean",
      initialValue: false,
    }),
    defineField({
      name: "hideOnDesktop",
      title: "Hide on Desktop",
      type: "boolean",
      initialValue: false,
    }),
  ],
});
